import random
choice=random.choice(["A giraffe has seven bones in its neck, which is the same as a human has, but they are much larger.",
                                    "Chilika is the largest lake in India.",
                                    "Hippos’ closest living relatives are the aquatic mammals: whales, dolphins and porpoises.",
                                    "A chameleon’s tongue is at least as long as its body, but it can grab prey in a fraction of a second.",
                                    "An eagle’s eyes are at least four times sharper than a human’s.",
                                    "To hover, hummingbirds may beat their wings up to 200 times per second.",
                                    "A jaguar can see in the dark six times better than a human.",
                                    "Sea otters have the densest fur of any mammal: a large male has around 800 million hairs, compared to just five million on a human.",
                                    "Cat fleas can jump to a height of up to 60 times their own body length.",
                                    "The lion has the loudest roar of all the big cats. It can be heard as far as 5km (3 miles) away.",
                                    "Emperor penguins can stay underwater for up to 27 minutes and dive as far as 500m deep.",
                                    "Humans share 98.8% of chimpanzee DNA. But even with DNA so similar, humans and chimps have around 35 million differences between them.",
                                    "When they find a source of water, wild Bactrian (two-humped) camels will drink as much as 50 litres (88 pints). They will even drink salty water, unlike other mammals.",
                                    "The Indian culture is one of the oldest in the world, going back to about 4,500 years.",
                                    "It can take a photon 40,000 years to travel from the core of the sun to the surface, but only 8 minutes to travel the rest of the way to earth.",
                                    "It would take 1,200,000 mosquitoes, each sucking once, to completely drain the average human of blood.",
                                    "Basically anything that melts can be made into glass. You just have to cool off a molten material before its molecules have time to realign into what they were before being melted.",
                                    "Written language was invented independently by the Egyptians, Sumerians, Chinese, and Mayans.",
                                    "If you were to remove all of the empty space from the atoms that make up every human on earth, the entire world population could fit into an apple.",
                                    "Honey does not spoil. You could feasibly eat 3000 year old honey.",
                                    "The Spanish national anthem has no words.",
                                    "The state sport of Maryland is jousting.",
                                    "Dead people can get goose bumps. ",
                                    "The Amazon is the world’s largest tropical rainforest.",
                                    "India has 22 official languages.",
                                    "The Sarus crane is one of the biggest cranes in India.",
                                    "Indian notes are made of cotton and cotton rag.",
                                    "The first time India participated in the Olympics was in 1900.",
                                    "The IPL has the second highest amount of money spent on it, after the NBA",
                                    "The only letter that doesn’t appear on the periodic table is J.",
                                    "If you point your car keys to your head, it increases the remote’s signal range.",
                                    "Iceland does not have a railway system.",
                                    "The color red doesn’t really make bulls angry; they are color-blind.",
                                    "65% of autistic kids are left-handed, and only 10% of people in general are left-handed",
                                    "Snakes can help predict earthquakes.",
                                    "A flock of crows is known as a murder.",
                                    "So far, two diseases have successfully been eradicated: smallpox and rinderpest.",
                                    "Cherophobia is an irrational fear of fun or happiness.",
                                    "If you lift a kangaroo’s tail off the ground it can’t hop.",
                                    "Movie trailers were originally shown after the movie, which is why they were called trailers.",
                                    "An eagle can kill a young deer and fly away with it.",
                                    "Saint Lucia is the only country in the world named after a woman.",
                                    "The following can be read forward and backwards: Do geese see God?",
                                    "A baby octopus is about the size of a flea when it is born.",
                                    "A swarm of 20,000 bees followed a car for two days because their queen was stuck inside.",
                                    "There is a total of 1,710 steps in the Eiffel Tower.",
                                    "Pirates wore earrings because they believed it improved their eyesight.",
                                    "The Twitter bird actually has a name – Larry.",
                                    "It snowed in the Sahara desert for 30 minutes on the 18th February 1979.",
                                    "An apple, potato, and onion all taste the same if you eat them with your nose plugged.",
                                    "The average person walks the equivalent of five times around the world in their lifetime.",
                                    "Tears contain a natural pain killer which reduces pain and improves your mood.",
                                    "Squirrels forget where they hide about half of their nuts.",
                                    "Mercury & Venus are the only 2 planets in our solar system that have no moons.",
                                    "The hottest planet in our solar system is Venus.",
                                    "Our solar system is 4.57 billion years old.",
                                    "A light-year is the distance covered by light in a single year.",
                                    "Footprints left on the Moon won’t disappear as there is no wind.",
                                    "Due to the Sun and Moon’s gravitational pull, we have tides.",
                                    "Pluto is smaller than the United States.",
                                    "There are more stars in space than there are grains of sand in the world.",
                                     "We know more about Mars and our Moon than we do about our oceans."])
print("Random fact:", choice)

